### ISSUE TITLE
Simple analytics - Add tracking events

### ISSUE THREAD

**Issue by AyronK** [AyronK/arpg-timeline#105]
- [x] On timeline event added to the calendar (group by calendar type)
- [x] On filter's applied
- [x] On entry with search params from the url
- [ ] On interact with the timeline widget (scroll? hover?)

**Comment by AyronK** [comment]
in progress

**Comment by AyronK** [comment]
#122
